/*
    Wn: A Server for the HTTP
    File: wn/content.h
    Version 2.4.3
    
    Copyright (C) 1998-2001  <by John Franks>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 1, or (at your option)
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/


#ifdef WNDEX
static char * 
#else
WN_CONST
static char * 
WN_CONST
#endif
mimelist[MAXMIME][2] = {
		{ "html", "text/html"},
		{ "htm", "text/html"},
		{ "txt", "text/plain"},
		{ "au", "audio/basic"},
		{ "snd", "audio/basic"},
		{ "mid", "audio/midi"},
		{ "midi", "audio/midi"},
		{ "aif", "audio/x-aiff"},
		{ "aiff", "audio/x-aiff"},
		{ "aifc", "audio/x-aiff"},
		{ "ra", "audio/x-pn-realaudio"},
		{ "rm", "audio/x-pn-realaudio"},
		{ "ram", "audio/x-pn-realaudio"},
		{ "wav", "audio/x-wav"},
		{ "qt", "video/quicktime"},
		{ "mov", "video/quicktime"},
		{ "mpeg", "video/mpeg"},
		{ "mpg", "video/mpeg"},
		{ "mpe", "video/mpeg"},
		{ "mws", "application/maple-v-r4"},
		{ "csm", "application/cu-seeme"},
		{ "cu", "application/cu-seeme"},
		{ "tsp", "application/dsptype"},
		{ "xls", "application/excel"},
		{ "hqx", "application/mac-binhex40"},
		{ "doc", "application/msword"},
		{ "dot", "application/msword"},
		{ "bin", "application/octet-stream"},
		{ "oda", "application/oda"},
		{ "pdf", "application/pdf"},
		{ "pgp", "application/pgp-signature"},
		{ "ps", "application/postscript"},
		{ "ai", "application/postscript"},
		{ "eps", "application/postscript"},
		{ "ppt", "application/powerpoint"},
		{ "rtf", "application/rtf"},
		{ "wp5", "application/wordperfect5.1"},
		{ "wk", "application/x-123"},
		{ "wz", "application/x-Wingz"},
		{ "bcpio", "application/x-bcpio"},
		{ "cpio", "application/x-cpio"},
		{ "csh", "application/x-csh"},
		{ "deb", "application/x-debian-package"},
		{ "dvi", "application/x-dvi"},
		{ "pfa", "application/x-font"},
		{ "pfb", "application/x-font"},
		{ "gsf", "application/x-font"},
		{ "pcf", "application/x-font"},
		{ "gtar", "application/x-gtar"},
		{ "tgz", "application/x-gtar"},
		{ "hdf", "application/x-hdf"},
		{ "phtml", "application/x-httpd-php"},
		{ "pht", "application/x-httpd-php"},
		{ "php", "application/x-httpd-php"},
		{ "php3", "application/x-httpd-php3"},
		{ "phps", "application/x-httpd-php3-source"},
		{ "php3p", "application/x-httpd-php3-preprocessed"},
		{ "class", "application/x-java"},
		{ "latex", "application/x-latex"},
		{ "frm", "application/x-maker"},
		{ "maker", "application/x-maker"},
		{ "frame", "application/x-maker"},
		{ "fm", "application/x-maker"},
		{ "fb", "application/x-maker"},
		{ "book", "application/x-maker"},
		{ "fbdoc", "application/x-maker"},
		{ "mif", "application/x-mif"},
		{ "com", "application/x-msdos-program"},
		{ "exe", "application/x-msdos-program"},
		{ "bat", "application/x-msdos-program"},
		{ "nc", "application/x-netcdf"},
		{ "cdf", "application/x-netcdf"},
		{ "o", "application/x-object"},
		{ "pl", "application/x-perl"},
		{ "pm", "application/x-perl"},
		{ "sh", "application/x-sh"},
		{ "shar", "application/x-shar"},
		{ "sv4cpio", "application/x-sv4cpio"},
		{ "sv4crc", "application/x-sv4crc"},
		{ "tar", "application/x-tar"},
		{ "tcl", "application/x-tcl"},
		{ "tex", "application/x-tex"},
		{ "gf", "application/x-tex-gf"},
		{ "pk", "application/x-tex-pk"},
		{ "texinfo", "application/x-texinfo"},
		{ "texi", "application/x-texinfo"},
		{ "bak", "application/x-trash"},
		{ "old", "application/x-trash"},
		{ "sik", "application/x-trash"},
		{ "t", "application/x-troff"},
		{ "tr", "application/x-troff"},
		{ "roff", "application/x-troff"},
		{ "man", "application/x-troff-man"},
		{ "me", "application/x-troff-me"},
		{ "ms", "application/x-troff-ms"},
		{ "ustar", "application/x-ustar"},
		{ "src", "application/x-wais-source"},
		{ "zip", "application/zip"},
		{ "gif", "image/gif"},
		{ "ief", "image/ief"},
		{ "jpeg", "image/jpeg"},
		{ "jpg", "image/jpeg"},
		{ "jpe", "image/jpeg"},
		{ "png", "image/png"},
		{ "tiff", "image/tiff"},
		{ "tif", "image/tiff"},
		{ "ras", "image/x-cmu-raster"},
		{ "bmp", "image/x-ms-bmp"},
		{ "pnm", "image/x-portable-anymap"},
		{ "pbm", "image/x-portable-bitmap"},
		{ "pgm", "image/x-portable-graymap"},
		{ "ppm", "image/x-portable-pixmap"},
		{ "rgb", "image/x-rgb"},
		{ "xbm", "image/x-xbitmap"},
		{ "xpm", "image/x-xpixmap"},
		{ "xwd", "image/x-xwindowdump"},
		{ "csv", "text/comma-separated-values"},
		{ "rtx", "text/richtext"},
		{ "tsv", "text/tab-separated-values"},
		{ "hpp", "text/x-c++hdr"},
		{ "hxx", "text/x-c++hdr"},
		{ "hh", "text/x-c++hdr"},
		{ "cpp", "text/x-c++src"},
		{ "cxx", "text/x-c++src"},
		{ "cc", "text/x-c++src"},
		{ "h", "text/x-chdr"},
		{ "c", "text/x-csrc"},
		{ "java", "text/x-java"},
		{ "moc", "text/x-moc"},
		{ "p", "text/x-pascal"},
		{ "pas", "text/x-pascal"},
		{ "etx", "text/x-setext"},
		{ "tcl", "text/x-tcl"},
		{ "tk", "text/x-tcl"},
		{ "tex", "text/x-tex"},
		{ "ltx", "text/x-tex"},
		{ "sty", "text/x-tex"},
		{ "cls", "text/x-tex"},
		{ "vcs", "text/x-vCalendar"},
		{ "vcf", "text/x-vCard"},
		{ "css", "text/css"},
		{ "dl", "video/dl"},
		{ "fli", "video/fli"},
		{ "gl", "video/gl"},
		{ "avi", "video/x-msvideo"},
		{ "movie", "video/x-sgi-movie"},
		{ "vrm", "x-world/x-vrml"},
		{ "vrml", "x-world/x-vrml"},
		{ "wrl", "x-world/x-vrml"},
		{ NULL, NULL }
};
